### ISSUE TITLE
Browsersync ignores host config, starts on localhost

### ISSUE THREAD

**Issue by mealeyst** [Va1/browser-sync-webpack-plugin#12]
Not a major issue, just something that I noticed. It appears that when I start up webpack, browsersync ignores the host setting in the BrowserSyncPlugin and instead opens a new tab in my internet browser at: localhost:4200 (note it doesn't appear to ignore the port).

sample config:

```
new BrowserSyncPlugin({
  host: 'local.example.com',
  port: 4200,
  proxy: 'http://local.example.com:3000/'
})
```

**Comment by Va1** [comment]
Hey!

Hm, let me check this out.

**Comment by mealeyst** [comment]
@Va1 Thank you so much for looking into this, if you need any other details as well I'd be happy to help.

**Comment by Va1** [comment]
@mealeyst 

Sorry for the delay, having too much stuff happening. However, I did look into issue and here's what I found:

1) yes, it does open localhost with the config you provided
2) no, it does not ignore `host` option, it just uses it for the external url. I guess, this is the proper behavior, as browser-sync server is being hosted on your localhost anyways, and can have aliases (I might be wrong about this, did not find anything related in browser-sync docs)
3) there is a way to do what you want. you should specify your desired host and it will be used as external url host, then you should add an `option` property ([docs](https://www.browsersync.io/docs/options/#option-open)), and set it to `external`, and it will open your host in the browser

What I put in config:
```javascript
var BrowserSyncPlugin = require('browser-sync-webpack-plugin');

module.exports = {
    entry: './src/entry.js',
    output: {
        path: './public',
        filename: 'bundle.js'
    },
    plugins: [
        new BrowserSyncPlugin({
            host: 'abrahadabra.foobar.com',
            port: 3030,
            server: { baseDir: ['public'] },
            open: 'external'
        })
    ]
};
```

What I see in console:
```
[BS] Access URLs:
 -----------------------------------------------
       Local: http://localhost:3030
    External: http://abrahadabra.foobar.com:3030
 -----------------------------------------------
          UI: http://localhost:3001
 UI External: http://abrahadabra.foobar.com:3001
 -----------------------------------------------
[BS] Serving files from: public
```

What I see in browser:
```
http://abrahadabra.foobar.com:3030/
```

**Comment by Va1** [comment]
I assume, the issue is closed.
