### ISSUE TITLE
Reload only change html

### ISSUE THREAD

**Issue by khmelevskii** [Va1/browser-sync-webpack-plugin#14]
I have config
```
....
    new BrowserSyncPlugin({
      notify: false,
      port: 8080,
      proxy: 'http://' + host + ':' + 3001 + '/',
    }, {
      reload: false,
    }),
```

but if I change *.html files, I want reload page

**Comment by Va1** [comment]
hey @khmelevskii ,

this is a plugin for webpack and reload is triggered when webpack says so. but webpack builds scripts and styles, not html, so it does not watch for html changes. so, I am not sure if there are any clean way to do what you want with this plugin (but I might be wrong).

Cheers,
Valentyn
