### ISSUE TITLE
Cancel webpack server for proxy

### ISSUE THREAD

**Issue by LeG3nDz** [Va1/browser-sync-webpack-plugin#15]
Hi,

Do you know if i can cancel webpack server for creat new proxy ? (for example, proxy my local server) :

    new BrowserSyncPlugin(
        {
            proxy: 'my-dev.lan',
            port: 8080,
            open: true,
            watchTask: true
        }
    )

Thank you !

**Comment by LeG3nDz** [comment]
Up :D

**Comment by Va1** [comment]
Hey yo @LeG3nDz !

Excuse me for being unreachable, I'm on high load for the last weeks =/

Though, I will help you asap. Please, rephrase your question in more detailed way, I did not get what you're trying to do.

**Comment by Va1** [comment]
And have a look [here](https://github.com/Va1/browser-sync-webpack-plugin#advanced). Is not it what you need (just sounds alike, I am not sure, as I've written above)?

**Comment by LeG3nDz** [comment]
Hi :)

It's okay, i can start proxy with my config (but previously it was not working)

Thanks to you !

**Comment by Va1** [comment]
Ah, nice! No problem. Resolved then :)
