### ISSUE TITLE
Index has mismatched function names

### ISSUE THREAD

**Issue by theMANDERSON** [Va1/browser-sync-webpack-plugin#17]
Recent update to index.js is throwing errors. The function name was updated but the prototype references and export object were not updated to match.

**Comment by theMANDERSON** [comment]
https://github.com/Va1/browser-sync-webpack-plugin/blob/master/index.js#L4

**Comment by lean** [comment]
`ReferenceError: Plugin is not defined`

**Comment by joshfriend** [comment]
#18 should fix it.

**Comment by joshfriend** [comment]
bec45e4 introduced the change that broke things. If you rename things in the API, you should _at least_ bump the **minor** version (not just the **patch** version). 

That way, people can use `~` in the version without getting a patch update that breaks everything.

**Comment by jeffj** [comment]
+1

**Comment by Va1** [comment]
Fixed with @joshfriend pull request. I did publish a fresh 1.0.3 to npm with the fix included. Sorry and thanks to everyone \o
