### ISSUE TITLE
Project has no git tags

### ISSUE THREAD

**Issue by joshfriend** [Va1/browser-sync-webpack-plugin#19]
There are 9 releases on NPM, and none of them have associated tags in git. I did some quick looking through the commit history and I think this is where the versions on NPM line up:

* 1.0.2: b4ae734
* 1.0.1: bcacec0
* 1.0.0: 8cf0109
* 0.2.2: d99abe2
* 0.2.1: 898abc2
* 0.2.0: 19f0c2c
* 0.1.3: 84ec739
* 0.1.2: b504bcb
* 0.1.1: a75efdc
* 0.1.0: 6370a0d

**Comment by Va1** [comment]
@joshfriend @	jeffj

Sound good, guys. Thanks a lot. I will create those tags shortly.

**Comment by Va1** [comment]
As I was unable to link older commits to the release, I did releases only for 1.0.3 and 1.1.0 versions. Though, I feel like these are the only mature ones.
