### ISSUE TITLE
Move browser-sync to peerDependencies

### ISSUE THREAD

**Issue by bjrmatos** [Va1/browser-sync-webpack-plugin#2]
I think is a good idea to move browser-sync to peerDependencies to keep track of automatic updates in the module

**Comment by Va1** [comment]
OK, makes sense. Thank you!

**Comment by Va1** [comment]
Done with https://github.com/Va1/browser-sync-webpack-plugin/commit/898abc2659342a2d80f28ffef89e7df51f3f00ad . Closing.

**Comment by bjrmatos** [comment]
:clap:

**Comment by bjrmatos** [comment]
i think that `>=2.x.x <3` or  `^2.x.x` will be much better

**Comment by Va1** [comment]
The reason I've put there latest versions is to be sure it will work, as I used the API of latest versions during development of the package.

 If you did test it with 2.0.0 and sure that it works, I will change this (or you can submit a PR).

**Comment by bjrmatos** [comment]
cool, let me test in browser-sync 2.0.0, if it is still working i'll send a PR
