### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by milewski** [Va1/browser-sync-webpack-plugin#31]
any chance of using this with electron?.. it doesnt server the files... electron does get those files from the localhost:3000 however the little snippet injected into browsers doesnt get injected into electron... causing it to not refresh automatically... so pretty much i can only see anything on browsers..

**Comment by Va1** [comment]
@Milewski hey!

sorry for the delayed reply.

i guess, if electron does not allow to include that stuff into page, reloading won't work. i think you should ask this question in browser-sync issues or some related place, as this looks like a browser-sync functionality stuff.

cheers!

**Comment by Va1** [comment]
i assume, this one is outdated. ping me if i am wrong
