### ISSUE TITLE
it seems the plugin does't work on macOS

### ISSUE THREAD

**Issue by xiadd** [Va1/browser-sync-webpack-plugin#37]
here is my related config:
![image](https://cloud.githubusercontent.com/assets/8351437/23498419/a0710b2a-ff62-11e6-9665-2c06769f5693.png)

I tested it in both win and mac.but it only works on win . Anything wrong?

**Comment by Va1** [comment]
@xiadd 
are there any errors/warnings? what exactly does not work?

**Comment by Intregrisist** [comment]
@xiadd I had to look at the source code, but it works only if `watch` is enabled in your webpack configuration.

**Comment by Va1** [comment]
i assume, this is outdated. ping me if i am wrong
