### ISSUE TITLE
Open Browser to 127.0.0.1 instead of localhost

### ISSUE THREAD

**Issue by mtpultz** [Va1/browser-sync-webpack-plugin#52]
Using the configuration below is it possible to have browser-sync open the browser to the host and port instead of defaulting to localhost and port.  A few of our projects have OAuth set to be 127.0.0.1 so we can't use localhost to authenticate.

```
new BrowserSyncPlugin(
  {
    host: 'http://127.0.0.1',
    port: 8888,
    proxy: 'http://127.0.0.1:8080'
  }
)
```

**Comment by Va1** [comment]
hi @mtpultz . these options are BrowserSync options and being passed directly to it's instance, so problems with them are out of scope of this project and you should open an issue for the [BrowserSync repository](https://github.com/BrowserSync/browser-sync). thanks
