### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by frizadiga** [Va1/browser-sync-webpack-plugin#55]

**Comment by malinushj** [comment]
@frizadiga Not sure but there hasn't been any activity from the creator in a long time. But you can safely still use this as it's only a wrapper for Browsersync as a webpack plugin. If you have a look through index.js it's quite easy what it does. Any other info you may need can be found on Browsersync's repo and website and also webpack's documentation for plugins.

**Comment by Va1** [comment]
@frizadiga no, it is not. i did not work on it for a while, but i'm gonna deploy some updates in nearest future
