### ISSUE TITLE
Initial Page Does Not Load When Using VS Code Generated App

### ISSUE THREAD

**Issue by devercify** [Va1/browser-sync-webpack-plugin#63]
I've created a new app using VS Code and the dotnet CLI:
`dotnet new angular`

I've added code from the GitHub page:
```
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');

module.exports = {
  // ...
  plugins: [
    new BrowserSyncPlugin(
      // BrowserSync options
      {
        // browse to http://localhost:3000/ during development
        host: 'localhost',
        port: 3000,
        // proxy the Webpack Dev Server endpoint
        // (which should be serving on http://localhost:3100/)
        // through BrowserSync
        proxy: 'http://localhost:3100/'
      },
      // plugin options
      {
        // prevent BrowserSync from reloading the page
        // and let Webpack Dev Server take care of this
        reload: false
      }
    )
  ]
```

Upon executing the command, 'dotnet run', a browser opens but the page never loads.

**Comment by Va1** [comment]
hi @tmlinc 

i am not a windows user and not familiar with dotnet stack so i can not test it right away. but i suggest to make sure you have proper webpack config instead of one from the plugin docs, which is shrinked down version intended just to show how the plugin should be set up.

**Comment by Va1** [comment]
for the absence of activity, i am closing this. thanks
