### ISSUE TITLE
enable only on certian ENV

### ISSUE THREAD

**Issue by theskillwithin** [Va1/browser-sync-webpack-plugin#81]
I want to only do browsersync when i do `yarn start-bs`

how do i do this in webpack config?

**Comment by malinushj** [comment]
@theskillwithin Hello!
using the config from the documentation, you can simply add a new line to `scripts` in `package.json`:
```json
"scripts": {
  "start-bs": "cross-env NODE_ENV=development webpack --watch",
  "prod": "cross-env NODE_ENV=production webpack"
},
```
Let me know if it works for you

**Comment by Va1** [comment]
the above comment is a valid solution. for the absence of further discussion, i close this. thank you, guys
