### ISSUE TITLE
Webpack 5 compatibility

### ISSUE THREAD

**Issue by davidmpaz** [Va1/browser-sync-webpack-plugin#83]
Hello,

First of all thanks for the work done on this plugin. This is not an issue, it is more a question about webpack 5 compatibility.

How it is planned the use of this plugin in webpack 5? 
Would it face some compatibility issue?

The reason behind this question is the realization of: symfony/webpack-encore#145

Best regards,
David

**Comment by Va1** [comment]
hi David,

sorry for delayed reply.

so far, all webpack versions were supported by me or by community supplying pull requests upon major webpack release. worth mentioning is that there was no big compatibility issues and that the webpack APIs used by this package barely change. but you never know, of course.

unless you or someone else of the community wants to check it now against webpack 5-beta, i would wait for webpack 5 release and see what happens.

regards

**Comment by tarponjargon** [comment]
Hi - just checking if there are plans to pursue wp5 compatibility.  I had browser-sync-webpack-plugin working with the last version wp4 but can't seem to get it working with 5

**Comment by Va1** [comment]
hi @tarponjargon

for the time being, support of Webpack 5 can be achieved only via community contribution.

this means, if you have a project where you've upgraded to Webpack v5 and this plugin now causes failure, i encourage you to investigate what is going wrong and submit a PR with a fix. i can help you with debugging and all administrative stuff, but, myself, i do not have a Webpack project (nor time to create/find one) to test with and patch things myself.

cheers

**Comment by Va1** [comment]
so, as was outlined by @Locheed in [this PR](https://github.com/Va1/browser-sync-webpack-plugin/pull/89), the plugin in its current state is compatible with Webpack 5. so, to avoid warnings/errors while installing it on Webpack 5 projects, I have merged the mentioned PR and bumped the version to [2.3.0](https://github.com/Va1/browser-sync-webpack-plugin/releases/tag/v2.3.0). thanks everyone for participating.
